Use `eltype` instead of `promote_type`
Otherwise we can get a StackOverflow error with large `samples`, eg

```julia
ERROR: LoadError: StackOverflowError:
Stacktrace:
 [1] promote_type(::Type, ::Type, ::Type, ::Type, ::Vararg{Type}) (repeats 600 times)
   @ Base ./promotion.jl:299
 [2] Observation(obs_dict::Dict{String, Any})
   @ EnsembleKalmanProcesses ~/.julia/packages/EnsembleKalmanProcesses/hifDM/src/Observations.jl:125
 [3] include(fname::String)
   @ Base.MainInclude ./client.jl:489
```